version: '3.7'

services:
  server:
    build: .
    volumes: 
      - /usr/src/app
    ports:
      - 5000:5000
    expose:
      - 5000
  
  client:
    build: ./client
    volumes:
      - /usr/src/app/client
    ports:
      - 3000:3000
    expose:
      - 3000
    stdin_open: true
    depends_on: 
      - server